const projects = [
 {title:'Village Damha IV',location:'São Carlos, SP',category:'residencial',image:'damha',gallery:['damha'],url:'village-damha-iv-sao-carlos-10'},
 {title:'Edifício Itapuã',location:'São Carlos, SP',category:'interiores',image:'itapua',gallery:['itapua'],url:'edificio-itapua-sao-carlos'},
 {title:'Parque Faber-Castell 5',location:'São Carlos, SP',category:'residencial',image:'faber',gallery:['faber'],url:'parque-faber-castell-5-sao-carlos'},
 {title:'Planalto Paraíso',location:'São Carlos, SP',category:'comercial',image:'planalto',gallery:['planalto'],url:'planalto-paraiso-sao-carlos'},
 {title:'Village Damha IV',location:'São Carlos, SP',category:'residencial',image:'damha2',gallery:['damha2'],url:'village-damha-iv-sao-carlos-9'},
 {title:'Centro',location:'Ibaté, SP',category:'residencial',image:'centro',gallery:['centro'],url:'centro-ibate-3'},
 {title:'Montreal',location:'São Carlos, SP',category:'residencial',image:'montreal',gallery:['montreal'],url:'montreal-sao-carlos'},
 {title:'Village Damha IV',location:'São Carlos, SP',category:'residencial',image:'damha3',gallery:['damha3'],url:'village-damha-iv-sao-carlos-8'},
 {title:'Centro',location:'Ibaté, SP',category:'comercial',image:'centro2',gallery:['centro2'],url:'centro-ibate-2'}
];
const labels={residencial:'Residencial',interiores:'Interiores',comercial:'Comercial'};
const grid=document.querySelector('#project-grid'),more=document.querySelector('#more-projects'),dialog=document.querySelector('#project-dialog');
let filter='all',expanded=false,currentProject,photoIndex=0,lastFocus;
function renderProjects(){const list=projects.filter(p=>filter==='all'||p.category===filter);grid.replaceChildren();list.slice(0,expanded?list.length:4).forEach(p=>{const card=document.createElement('button');card.className='project-card';card.setAttribute('aria-label',`Ver projeto ${p.title}, ${p.location}`);card.innerHTML=`<div class="project-image"><img src="/assets/${p.image}.webp" alt="Projeto ${p.title} em ${p.location}" width="768" height="614" loading="lazy"><span class="project-arrow" aria-hidden="true">↗</span></div><div class="project-meta"><div><h3>${p.title}</h3><p>${p.location}</p></div><span>${labels[p.category]}</span></div>`;card.addEventListener('click',()=>openProject(p));grid.append(card)});more.hidden=list.length<=4;more.innerHTML=expanded?'Mostrar menos <span>↑</span>':'Ver mais projetos <span>↓</span>'}
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{filter=button.dataset.filter;expanded=false;document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});renderProjects()}));
more.addEventListener('click',()=>{expanded=!expanded;renderProjects();if(!expanded)document.querySelector('#projetos').scrollIntoView({behavior:'smooth'})});
function updatePhoto(){const img=document.querySelector('#dialog-image');img.src=`/assets/${currentProject.gallery[photoIndex]}.webp`;img.alt=`Projeto ${currentProject.title} em ${currentProject.location}, imagem ${photoIndex+1}`;document.querySelector('#photo-count').textContent=`${photoIndex+1} / ${currentProject.gallery.length}`;document.querySelectorAll('.photo-arrow').forEach(b=>b.hidden=currentProject.gallery.length<2)}
function openProject(p){lastFocus=document.activeElement;currentProject=p;photoIndex=0;document.querySelector('#dialog-title').textContent=p.title;document.querySelector('#dialog-location').textContent=p.location;document.querySelector('#dialog-category').textContent=labels[p.category];document.querySelector('#dialog-contact').href=`https://wa.me/5516996430515?text=${encodeURIComponent('Olá, equipe GPG! Gostei do projeto '+p.title+' e quero conversar sobre uma ideia.')}`;updatePhoto();dialog.showModal();document.body.classList.add('modal-open')}
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');lastFocus?.focus()});
function changePhoto(n){photoIndex=(photoIndex+n+currentProject.gallery.length)%currentProject.gallery.length;updatePhoto()}
document.querySelector('#previous-photo').addEventListener('click',()=>changePhoto(-1));document.querySelector('#next-photo').addEventListener('click',()=>changePhoto(1));dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')changePhoto(-1);if(e.key==='ArrowRight')changePhoto(1)});
const menu=document.querySelector('.menu'),nav=document.querySelector('#navigation');function closeMenu(){menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Abrir menu');nav.classList.remove('open')}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');nav.classList.toggle('open',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});document.addEventListener('click',e=>{if(!e.target.closest('.header'))closeMenu()});window.matchMedia('(min-width:761px)').addEventListener('change',e=>{if(e.matches)closeMenu()});
window.addEventListener('scroll',()=>document.querySelector('.header').classList.toggle('scrolled',window.scrollY>30),{passive:true});document.querySelector('#year').textContent=new Date().getFullYear();renderProjects();
